import { Exercise } from "@/types/model";

export const mockExercises: Exercise[] = [
  {
    id: "1",
    title: "Push Up",
    description: "Latihan dada dan trisep dengan berat badan sendiri.",
    body_part: "Chest",
    equipment: "Body Weight",
    target: "Pectorals",
    secondary_muscles: ["Triceps", "Shoulders"],
    instructions: [
      "Posisikan tangan selebar bahu di lantai.",
      "Turunkan badan hingga dada hampir menyentuh lantai.",
      "Dorong kembali ke posisi awal.",
    ],
    difficulty: "Beginner",
    category: "Strength",
    created_at: "2026-01-10 09:00:00",
    updated_at: "2026-01-10 09:00:00",
  },
  {
    id: "2",
    title: "Barbell Squat",
    description: "Latihan kaki utama untuk kekuatan paha dan glutes.",
    body_part: "Legs",
    equipment: "Barbell",
    target: "Quadriceps",
    secondary_muscles: ["Glutes", "Hamstrings"],
    instructions: [
      "Posisikan barbell di atas bahu.",
      "Turunkan badan hingga paha sejajar lantai.",
      "Berdiri kembali dengan mendorong tumit.",
    ],
    difficulty: "Intermediate",
    category: "Strength",
    created_at: "2026-02-05 10:15:00",
    updated_at: "2026-02-05 10:15:00",
  },
  {
    id: "3",
    title: "Deadlift",
    description: "Gerakan compound untuk punggung bawah dan posterior chain.",
    body_part: "Back",
    equipment: "Barbell",
    target: "Lower Back",
    secondary_muscles: ["Glutes", "Hamstrings", "Traps"],
    instructions: [
      "Berdiri dengan kaki selebar pinggul di depan bar.",
      "Genggam bar dan angkat dengan punggung lurus.",
      "Kunci pinggul di posisi atas.",
    ],
    difficulty: "Advanced",
    category: "Strength",
    created_at: "2026-03-01 08:45:00",
    updated_at: "2026-03-01 08:45:00",
  },
  {
    id: "4",
    title: "Dumbbell Shoulder Press",
    description: "Latihan bahu dengan dumbbell dari posisi duduk.",
    body_part: "Shoulders",
    equipment: "Dumbbell",
    target: "Deltoids",
    secondary_muscles: ["Triceps", "Upper Chest"],
    instructions: [
      "Duduk dengan punggung tegak, dumbbell setinggi bahu.",
      "Dorong dumbbell ke atas hingga lengan lurus.",
      "Turunkan perlahan ke posisi awal.",
    ],
    difficulty: "Intermediate",
    category: "Strength",
    created_at: "2026-04-02 13:10:00",
    updated_at: "2026-04-02 13:10:00",
  },
  {
    id: "5",
    title: "Plank",
    description: "Latihan isometrik untuk stabilitas otot inti.",
    body_part: "Core",
    equipment: "Body Weight",
    target: "Abs",
    secondary_muscles: ["Shoulders", "Glutes"],
    instructions: [
      "Posisikan siku di bawah bahu dan luruskan badan.",
      "Kencangkan otot perut dan bokong.",
      "Tahan posisi selama 30-60 detik.",
    ],
    difficulty: "Beginner",
    category: "Core",
    created_at: "2026-05-07 15:40:00",
    updated_at: "2026-05-07 15:40:00",
  },
  {
    id: "6",
    title: "Pull Up",
    description: "Latihan punggung atas dengan menggantung di pull-up bar.",
    body_part: "Back",
    equipment: "Pull-up Bar",
    target: "Lats",
    secondary_muscles: ["Biceps", "Shoulders"],
    instructions: [
      "Genggam bar dengan tangan selebar bahu.",
      "Tarik badan hingga dagu melewati bar.",
      "Turunkan perlahan hingga lengan lurus.",
    ],
    difficulty: "Intermediate",
    category: "Strength",
    created_at: "2026-06-11 10:05:00",
    updated_at: "2026-06-11 10:05:00",
  },
  {
    id: "7",
    title: "Barbell Bench Press",
    description: "Latihan dada utama dengan barbell di atas bench.",
    body_part: "Chest",
    equipment: "Barbell",
    target: "Pectorals",
    secondary_muscles: ["Triceps", "Shoulders"],
    instructions: [
      "Berbaring di bench dengan kaki menapak lantai.",
      "Turunkan bar hingga menyentuh dada.",
      "Dorong bar kembali ke atas hingga lengan lurus.",
    ],
    difficulty: "Intermediate",
    category: "Strength",
    created_at: "2026-07-03 12:25:00",
    updated_at: "2026-07-03 12:25:00",
  },
  {
    id: "8",
    title: "Dumbbell Bicep Curl",
    description: "Latihan isolasi untuk otot lengan depan.",
    body_part: "Arms",
    equipment: "Dumbbell",
    target: "Biceps",
    secondary_muscles: ["Forearms"],
    instructions: [
      "Berdiri tegak dengan dumbbell di kedua tangan.",
      "Tekuk siku dan angkat dumbbell ke arah bahu.",
      "Turunkan perlahan ke posisi awal.",
    ],
    difficulty: "Beginner",
    category: "Strength",
    created_at: "2026-07-20 09:30:00",
    updated_at: "2026-07-20 09:30:00",
  },
  {
    id: "9",
    title: "Walking Lunge",
    description: "Latihan kaki unilateral untuk glutes dan paha.",
    body_part: "Legs",
    equipment: "Dumbbell",
    target: "Glutes",
    secondary_muscles: ["Quadriceps", "Hamstrings"],
    instructions: [
      "Pegang dumbbell dan langkahkan satu kaki ke depan.",
      "Turunkan lutut belakang hingga hampir menyentuh lantai.",
      "Dorong ke depan dan ulangi dengan kaki satunya.",
    ],
    difficulty: "Beginner",
    category: "Strength",
    created_at: "2026-08-04 16:10:00",
    updated_at: "2026-08-04 16:10:00",
  },
  {
    id: "10",
    title: "Burpee",
    description: "Gerakan full-body intensitas tinggi untuk kardio dan kekuatan.",
    body_part: "Full Body",
    equipment: "Body Weight",
    target: "Cardiovascular",
    secondary_muscles: ["Chest", "Legs", "Shoulders"],
    instructions: [
      "Mulai dari posisi berdiri lalu jongkok dan letakkan tangan di lantai.",
      "Lompatkan kaki ke belakang ke posisi plank.",
      "Lompat kembali ke depan lalu melompat ke atas.",
    ],
    difficulty: "Advanced",
    category: "Cardio",
    created_at: "2026-08-19 07:45:00",
    updated_at: "2026-08-19 07:45:00",
  },
];
